package engine

// CheckInfo describes a single compliance check for the admin UI.
type CheckInfo struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Severity    string       `json:"severity"`
	Integration string       `json:"integration"`
	Frameworks  []string     `json:"frameworks"` // which frameworks this check belongs to
	Controls    []ControlRef `json:"controls"`
}

// Registry is the canonical list of all checks, used by the admin checks browser.
var Registry = []CheckInfo{
	// ── AWS IAM ──────────────────────────────────────────────────────────────
	{ID: "aws_iam_root_mfa", Title: "Root account MFA enabled", Severity: "critical", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.5"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "aws_iam_root_access_keys", Title: "No root account access keys", Severity: "critical", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.4"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "aws_iam_console_mfa", Title: "MFA enabled for all IAM users", Severity: "critical", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "aws_iam_password_policy", Title: "IAM password policy configured", Severity: "high", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.1"), PCIDSS("8.3.6")}},
	{ID: "aws_iam_unused_credentials", Title: "No unused IAM credentials (90+ days)", Severity: "high", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.2"}, ISO27001("A.9.2.5"), PCIDSS("8.2.6")}},
	{ID: "aws_iam_access_key_rotation", Title: "Access keys rotated within 90 days", Severity: "high", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.3"), PCIDSS("8.2.9")}},
	{ID: "aws_iam_no_direct_admin", Title: "No direct AdministratorAccess policies", Severity: "high", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "aws_iam_access_analyzer", Title: "IAM Access Analyzer enabled", Severity: "medium", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.1.2"), PCIDSS("7.2.3")}},

	// ── AWS S3 ───────────────────────────────────────────────────────────────
	{ID: "aws_s3_account_public_block", Title: "S3 account-level public access block", Severity: "critical", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_s3_encryption", Title: "S3 bucket server-side encryption", Severity: "high", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_s3_versioning", Title: "S3 bucket versioning enabled", Severity: "medium", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "aws_s3_logging", Title: "S3 access logging enabled", Severity: "medium", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── AWS CloudTrail ────────────────────────────────────────────────────────
	{ID: "aws_cloudtrail_enabled", Title: "CloudTrail enabled in all regions", Severity: "critical", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_ct_log_validation", Title: "CloudTrail log file validation enabled", Severity: "medium", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.4.2"), PCIDSS("10.5.2")}},

	// ── AWS Security Groups ───────────────────────────────────────────────────
	{ID: "aws_sg_no_open_ssh", Title: "SSH not open to 0.0.0.0/0", Severity: "critical", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "aws_sg_no_open_rdp", Title: "RDP not open to 0.0.0.0/0", Severity: "critical", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},

	// ── AWS KMS ───────────────────────────────────────────────────────────────
	{ID: "aws_kms_key_rotation", Title: "KMS customer keys auto-rotate annually", Severity: "medium", Integration: "AWS/KMS",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.10.1.2"), PCIDSS("3.7.4")}},

	// ── AWS RDS ───────────────────────────────────────────────────────────────
	{ID: "aws_rds_encryption", Title: "RDS storage encryption enabled", Severity: "high", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_rds_not_public", Title: "RDS instances not publicly accessible", Severity: "critical", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_rds_ssl_enforcement", Title: "RDS instances enforce SSL/TLS in transit", Severity: "high", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "aws_rds_deletion_protection", Title: "RDS instances have deletion protection enabled", Severity: "medium", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "aws_rds_backup", Title: "RDS automated backups retain ≥ 7 days", Severity: "high", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.310(d)(2)(iv)"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "aws_rds_iam_auth", Title: "RDS IAM database authentication enabled", Severity: "medium", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "aws_rds_multi_az", Title: "RDS instances have Multi-AZ enabled", Severity: "medium", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "A1.2"}, ISO27001("A.17.2.1"), PCIDSS("12.3.4")}},
	{ID: "aws_rds_minor_upgrade", Title: "RDS auto minor version upgrade enabled", Severity: "low", Integration: "AWS/RDS",
		Frameworks: []string{"cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkCIS, "2.3.2"}, ISO27001("A.12.6.1"), PCIDSS("6.3.3")}},

	// ── AWS EC2 Database ──────────────────────────────────────────────────────
	{ID: "aws_ec2_db_ebs_encrypted", Title: "EC2 database instance EBS volumes are encrypted", Severity: "high", Integration: "AWS/EC2-Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_ec2_db_no_public_ip", Title: "EC2 database instances have no public IP address", Severity: "critical", Integration: "AWS/EC2-Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_ec2_db_sg_exposure", Title: "EC2 database security groups do not expose DB ports to internet", Severity: "critical", Integration: "AWS/EC2-Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "aws_ec2_db_cloudwatch_logs", Title: "EC2 database instances have CloudWatch log groups configured", Severity: "high", Integration: "AWS/EC2-Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── AWS RDS Audit ─────────────────────────────────────────────────────────
	{ID: "aws_rds_audit_logging", Title: "RDS instances export audit/error logs to CloudWatch Logs", Severity: "high", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_cloudtrail_rds_events", Title: "CloudTrail records RDS data plane events", Severity: "medium", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── Kubernetes Database ───────────────────────────────────────────────────
	{ID: "k8s_db_pvc_encrypted", Title: "Database pod PVCs use encrypted StorageClass", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "k8s_db_no_public_service", Title: "No database ports exposed via LoadBalancer or NodePort", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "k8s_db_audit_logging", Title: "Kubernetes API server audit policy or runtime security agent present", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── Terraform Database ────────────────────────────────────────────────────
	{ID: "tf_rds_ssl_mode", Title: "RDS parameter group enforces SSL/TLS", Severity: "high", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "tf_db_hardcoded_password", Title: "No hardcoded passwords in Terraform RDS resources", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},

	// ── AWS RDS Access ────────────────────────────────────────────────────────
	{ID: "aws_rds_overprivileged_iam", Title: "No IAM principals with broad RDS access", Severity: "high", Integration: "AWS/DB-Access",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "aws_rds_no_master_user_exposed", Title: "RDS instances do not use default master usernames", Severity: "medium", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "aws_secrets_manager_rotation", Title: "DB secrets in Secrets Manager have rotation enabled", Severity: "high", Integration: "AWS/DB-Access",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.9")}},

	// ── Kubernetes DB Access ──────────────────────────────────────────────────
	{ID: "k8s_db_not_root", Title: "Database containers do not run as root", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_db_secret_not_configmap", Title: "No database credentials stored in ConfigMaps", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},

	// ── AWS GuardDuty ─────────────────────────────────────────────────────────
	{ID: "aws_guardduty_enabled", Title: "GuardDuty threat detection enabled", Severity: "high", Integration: "AWS/GuardDuty",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},

	// ── ISO 27001 specific ────────────────────────────────────────────────────
	{ID: "iso27001_asset_tagging", Title: "EC2 instances tagged with Owner and Environment", Severity: "medium", Integration: "AWS/ISO27001",
		Frameworks: []string{"iso27001"},
		Controls:   []ControlRef{ISO27001("A.8.1"), ISO27001("A.8.2")}},
	{ID: "iso27001_rds_multi_az", Title: "RDS instances have Multi-AZ enabled", Severity: "high", Integration: "AWS/ISO27001",
		Frameworks: []string{"iso27001"},
		Controls:   []ControlRef{ISO27001("A.17.1.2"), ISO27001("A.17.2.1")}},
	{ID: "iso27001_rds_backup_retention", Title: "RDS backup retention ≥ 7 days", Severity: "high", Integration: "AWS/ISO27001",
		Frameworks: []string{"iso27001"},
		Controls:   []ControlRef{ISO27001("A.12.3.1"), ISO27001("A.17.1.2")}},
	{ID: "iso27001_alb_https_redirect", Title: "ALB HTTP redirects to HTTPS", Severity: "high", Integration: "AWS/ISO27001",
		Frameworks: []string{"iso27001"},
		Controls:   []ControlRef{ISO27001("A.10.1.1"), ISO27001("A.13.2.3")}},
	{ID: "iso27001_cloudwatch_alarms", Title: "CloudWatch alarms for incident detection", Severity: "medium", Integration: "AWS/ISO27001",
		Frameworks: []string{"iso27001"},
		Controls:   []ControlRef{ISO27001("A.16.1.2"), ISO27001("A.12.4.1")}},

	// ── PCI DSS specific ──────────────────────────────────────────────────────
	{ID: "pcidss_inspector_enabled", Title: "AWS Inspector v2 enabled", Severity: "high", Integration: "AWS/PCIDSS",
		Frameworks: []string{"pcidss"},
		Controls:   []ControlRef{PCIDSS("6.3.2"), PCIDSS("11.3.1")}},
	{ID: "pcidss_guardduty_malware", Title: "GuardDuty malware protection enabled", Severity: "critical", Integration: "AWS/PCIDSS",
		Frameworks: []string{"pcidss"},
		Controls:   []ControlRef{PCIDSS("5.2.1"), PCIDSS("5.3.2")}},
	{ID: "pcidss_ebs_encrypted", Title: "All EBS volumes encrypted", Severity: "high", Integration: "AWS/PCIDSS",
		Frameworks: []string{"pcidss"},
		Controls:   []ControlRef{PCIDSS("3.5.1"), PCIDSS("3.7.1")}},
	{ID: "pcidss_vpc_flow_logs", Title: "VPC Flow Logs enabled on all VPCs", Severity: "high", Integration: "AWS/PCIDSS",
		Frameworks: []string{"pcidss"},
		Controls:   []ControlRef{PCIDSS("10.2.1"), PCIDSS("10.3.2")}},
	{ID: "pcidss_ecr_scan_on_push", Title: "ECR repositories scan images on push", Severity: "high", Integration: "AWS/PCIDSS",
		Frameworks: []string{"pcidss"},
		Controls:   []ControlRef{PCIDSS("6.3.2"), PCIDSS("11.3.1")}},

	// ── GitHub ────────────────────────────────────────────────────────────────
	{ID: "github_2fa_required", Title: "2FA required for all org members", Severity: "critical", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "github_branch_protection", Title: "Default branch protection enabled", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.1.4"), PCIDSS("6.2.4")}},
	{ID: "github_secret_scanning", Title: "Secret scanning enabled", Severity: "critical", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.1"), PCIDSS("6.3.2")}},
	{ID: "github_db_credentials", Title: "No database credentials committed to source code", Severity: "critical", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},

	// ── GCP ───────────────────────────────────────────────────────────────────
	{ID: "gcp_logging_enabled", Title: "Cloud Audit Logging enabled", Severity: "high", Integration: "GCP",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_storage_not_public", Title: "GCS buckets not publicly accessible", Severity: "critical", Integration: "GCP",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_sql_require_ssl", Title: "Cloud SQL requires SSL connections", Severity: "high", Integration: "GCP",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},

	// ── Kubernetes ────────────────────────────────────────────────────────────
	{ID: "k8s_no_privileged_containers", Title: "No privileged containers running", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_rbac_enabled", Title: "RBAC enabled on cluster", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_network_policies", Title: "Network policies defined", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},

	// ── Terraform ─────────────────────────────────────────────────────────────
	{ID: "tf_sg_ssh_restricted", Title: "SSH not open to 0.0.0.0/0 in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "tf_rds_encrypted", Title: "RDS storage_encrypted = true in Terraform", Severity: "high", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "tf_remote_backend", Title: "Terraform remote backend configured", Severity: "high", Integration: "Terraform",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "tf_no_hardcoded_secrets", Title: "No hardcoded secrets in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.3"), PCIDSS("8.2.1")}},

	// ── Database (comply db scan) ─────────────────────────────────────────────
	{ID: "db_pii_column_detection", Title: "No PII-named columns without documented controls", Severity: "high", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.18.1.4"), PCIDSS("3.3.1")}},
	{ID: "db_pii_data_sampling", Title: "No unencrypted PII in sampled database rows", Severity: "critical", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(e)(2)(ii)"}, ISO27001("A.18.1.4"), PCIDSS("3.3.1")}},
	{ID: "db_tls_connection_test", Title: "Database server enforces TLS — no plaintext connections", Severity: "critical", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "db_rls_on_pii_tables", Title: "Row Level Security enabled on PII tables", Severity: "high", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.1.2"), PCIDSS("7.2.2")}},
	{ID: "db_schema_audit_table", Title: "Audit log table exists in database schema", Severity: "medium", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "db_default_accounts", Title: "No default database accounts active (postgres, root, sa, mysql…)", Severity: "critical", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "db_unused_accounts", Title: "No database accounts inactive for 90+ days", Severity: "medium", Integration: "Database",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.312(a)(1)"}, ISO27001("A.9.2.5"), PCIDSS("8.2.6")}},

	// ── AWS Macie ─────────────────────────────────────────────────────────────
	{ID: "aws_macie_enabled", Title: "Amazon Macie is enabled and actively scanning S3 for PII", Severity: "high", Integration: "AWS/Macie",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.18.1.4"), PCIDSS("3.3.1")}},
	{ID: "aws_macie_findings", Title: "No active HIGH/CRITICAL Macie PII findings in S3", Severity: "critical", Integration: "AWS/Macie",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.18.1.4"), PCIDSS("3.3.1")}},

	// ── GCP DLP ───────────────────────────────────────────────────────────────
	{ID: "gcp_dlp_job_active", Title: "GCP DLP inspection job scanning Cloud Storage for PII", Severity: "high", Integration: "GCP",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.18.1.4"), PCIDSS("3.3.1")}},

	// ── AWS IAM (additional) ──────────────────────────────────────────────────
	{ID: "aws_iam_root_hardware_mfa", Title: "Root account uses hardware MFA device", Severity: "critical", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.6"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "aws_iam_users_in_groups", Title: "IAM users receive permissions via groups only", Severity: "medium", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "1.15"}, ISO27001("A.9.2.2"), PCIDSS("7.2.1")}},
	{ID: "aws_iam_support_role", Title: "IAM support role with AWSSupportAccess exists", Severity: "low", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "1.17"}, ISO27001("A.6.1.2"), PCIDSS("12.5.1")}},
	{ID: "aws_iam_one_key_per_user", Title: "One active access key per IAM user", Severity: "medium", Integration: "AWS/IAM",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.13"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},

	// ── AWS S3 (additional) ───────────────────────────────────────────────────
	{ID: "aws_s3_public_access_block", Title: "S3 bucket-level public access block enabled", Severity: "critical", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_s3_mfa_delete", Title: "S3 MFA delete enabled", Severity: "high", Integration: "AWS/S3",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkCIS, "2.1.3"}, ISO27001("A.12.3.1"), PCIDSS("10.5.2")}},

	// ── AWS CloudTrail (additional) ───────────────────────────────────────────
	{ID: "aws_cloudtrail_logging", Title: "CloudTrail logging is active", Severity: "critical", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_cloudtrail_multiregion", Title: "CloudTrail multi-region trail active", Severity: "high", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_cloudtrail_log_validation", Title: "CloudTrail log file validation enabled", Severity: "medium", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.2"}, ISO27001("A.12.4.2"), PCIDSS("10.5.2")}},
	{ID: "aws_ct_cloudwatch", Title: "CloudTrail integrated with CloudWatch Logs", Severity: "medium", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.4"}, ISO27001("A.12.4.1"), PCIDSS("10.4.1")}},
	{ID: "aws_ct_s3_public", Title: "CloudTrail S3 bucket not publicly accessible", Severity: "critical", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.3"}, ISO27001("A.12.4.2"), PCIDSS("10.5.1")}},
	{ID: "aws_ct_kms", Title: "CloudTrail logs encrypted with KMS CMK", Severity: "medium", Integration: "AWS/CloudTrail",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkCIS, "3.7"}, ISO27001("A.10.1.1"), PCIDSS("10.5.1")}},

	// ── AWS CloudWatch Alarms ─────────────────────────────────────────────────
	{ID: "aws_cw_alarm_root_login", Title: "CloudWatch alarm: root account login", Severity: "high", Integration: "AWS/CloudWatch",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.3"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1.1")}},
	{ID: "aws_cw_alarm_unauth_api", Title: "CloudWatch alarm: unauthorized API calls", Severity: "high", Integration: "AWS/CloudWatch",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1.3")}},
	{ID: "aws_cw_alarm_no_mfa_console", Title: "CloudWatch alarm: console sign-in without MFA", Severity: "high", Integration: "AWS/CloudWatch",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "3.2"}, ISO27001("A.9.4.2"), PCIDSS("10.2.1.2")}},
	{ID: "aws_cw_alarm_iam_policy_change", Title: "CloudWatch alarm: IAM policy changes", Severity: "medium", Integration: "AWS/CloudWatch",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.4"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── AWS Security Groups (actual IDs used by checker) ─────────────────────
	{ID: "aws_sg_open_ssh", Title: "No security groups open SSH to 0.0.0.0/0", Severity: "critical", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "4.1"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "aws_sg_open_rdp", Title: "No security groups open RDP to 0.0.0.0/0", Severity: "critical", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "4.2"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "aws_sg_unrestricted_ports", Title: "No security groups expose high-risk ports to internet", Severity: "high", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "4.3"}, ISO27001("A.13.1.1"), PCIDSS("1.2.2")}},
	{ID: "aws_sg_default_restricted", Title: "Default security group restricts all traffic", Severity: "medium", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.4"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},
	{ID: "aws_vpc_flow_logs", Title: "VPC flow logs enabled", Severity: "medium", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "3.9"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── AWS Encryption ────────────────────────────────────────────────────────
	{ID: "aws_ebs_encryption", Title: "EBS default encryption enabled", Severity: "high", Integration: "AWS/EC2",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "2.2.1"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_efs_encryption", Title: "EFS encryption at rest enabled", Severity: "high", Integration: "AWS/EFS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "2.4.1"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_kms_rotation", Title: "KMS customer keys have annual rotation enabled", Severity: "medium", Integration: "AWS/KMS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkCIS, "3.8"}, ISO27001("A.10.1.2"), PCIDSS("3.7.4")}},
	{ID: "aws_rds_public_snapshot", Title: "No public RDS snapshots", Severity: "critical", Integration: "AWS/RDS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},

	// ── AWS Monitoring & Config ───────────────────────────────────────────────
	{ID: "aws_secrets_manager", Title: "Secrets Manager in use for sensitive credentials", Severity: "high", Integration: "AWS/SecretsManager",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},
	{ID: "aws_config_enabled", Title: "AWS Config enabled and recording", Severity: "high", Integration: "AWS/Config",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.5"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_inspector_enabled", Title: "AWS Inspector v2 enabled", Severity: "medium", Integration: "AWS/Inspector",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)(ii)(B)"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "aws_securityhub_enabled", Title: "Security Hub enabled", Severity: "medium", Integration: "AWS/SecurityHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},
	{ID: "aws_sns_topics", Title: "SNS topics exist for CloudWatch alarm notifications", Severity: "low", Integration: "AWS/SNS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── AWS EKS (actual IDs + additional) ────────────────────────────────────
	{ID: "aws_eks_endpoint_public", Title: "EKS API endpoint not open to 0.0.0.0/0", Severity: "critical", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.4.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_eks_secrets_encryption", Title: "EKS secrets encrypted at rest with KMS", Severity: "high", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "5.3.1"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "aws_eks_logging", Title: "EKS control plane logging (api/audit/auth) enabled", Severity: "high", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "5.1.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "aws_eks_imdsv2", Title: "EKS node groups enforce IMDSv2", Severity: "medium", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.4.2"}, ISO27001("A.13.1.3"), PCIDSS("6.3.3")}},
	{ID: "aws_eks_pod_security", Title: "EKS pod security admission labels enforced", Severity: "high", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.1"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "aws_eks_anonymous_auth", Title: "EKS no anonymous API access (system:anonymous unbound)", Severity: "critical", Integration: "AWS/EKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "5.1.1"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},

	// ── AWS ECR (full set) ────────────────────────────────────────────────────
	{ID: "aws_ecr_scan_on_push", Title: "ECR repositories scan images on push", Severity: "high", Integration: "AWS/ECR",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "5.1"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "aws_ecr_vulnerabilities", Title: "No CRITICAL/HIGH CVEs in latest ECR images", Severity: "critical", Integration: "AWS/ECR",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "5.2"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "aws_ecr_immutable_tags", Title: "ECR image tags are immutable", Severity: "medium", Integration: "AWS/ECR",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "5.3"}, ISO27001("A.12.5.1"), PCIDSS("6.3.2")}},
	{ID: "aws_ecr_lifecycle_policy", Title: "ECR lifecycle policy configured", Severity: "low", Integration: "AWS/ECR",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "5.4"}, ISO27001("A.12.3.1"), PCIDSS("6.3.2")}},
	{ID: "aws_ecr_repo_not_public", Title: "ECR repository policy does not allow public access", Severity: "critical", Integration: "AWS/ECR",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},

	// ── AWS WAF / ALB / Lambda / Backup / Route53 / Org ──────────────────────
	{ID: "aws_waf_enabled", Title: "WAFv2 Web ACL associated with ALB or CloudFront", Severity: "high", Integration: "AWS/WAF",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, ISO27001("A.13.1.1"), PCIDSS("6.4.1")}},
	{ID: "aws_alb_https_only", Title: "ALB listeners redirect HTTP to HTTPS", Severity: "high", Integration: "AWS/ELB",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(2)(ii)"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "aws_lambda_public_url", Title: "Lambda function URLs are not publicly unauthenticated", Severity: "high", Integration: "AWS/Lambda",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "aws_backup_vault", Title: "AWS Backup vault configured for key resources", Severity: "high", Integration: "AWS/Backup",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.308(a)(7)"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "aws_route53_dnssec", Title: "Route53 DNSSEC enabled on public hosted zones", Severity: "medium", Integration: "AWS/Route53",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "aws_org_scp", Title: "AWS Organizations baseline SCPs active", Severity: "high", Integration: "AWS/Organizations",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "aws_cw_log_metric_filters", Title: "CloudWatch metric filters configured for key events", Severity: "medium", Integration: "AWS/CloudWatch",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── GCP IAM ───────────────────────────────────────────────────────────────
	{ID: "gcp_iam_sa_keys", Title: "No service accounts with user-managed keys", Severity: "high", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.4"}, ISO27001("A.9.2.3"), PCIDSS("8.2.9")}},
	{ID: "gcp_org_domain_restrict", Title: "Domain-restricted sharing org policy enforced", Severity: "high", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.8"}, ISO27001("A.9.1.2"), PCIDSS("7.2.3")}},
	{ID: "gcp_iam_primitive_roles", Title: "No users with primitive Owner/Editor roles", Severity: "high", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "1.1"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "gcp_iam_gmail", Title: "No gmail.com accounts in project IAM bindings", Severity: "high", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.2"}, ISO27001("A.9.2.2"), PCIDSS("8.2.1")}},
	{ID: "gcp_iam_sa_owner", Title: "No service account has project Owner role", Severity: "critical", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "1.5"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "gcp_iam_sa_key_age", Title: "Service account keys rotated within 90 days", Severity: "high", Integration: "GCP/IAM",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "1.7"}, ISO27001("A.9.4.3"), PCIDSS("8.2.9")}},

	// ── GCP Audit & Logging ───────────────────────────────────────────────────
	{ID: "gcp_audit_logs", Title: "Cloud Audit Logs DATA_READ+WRITE enabled for allServices", Severity: "high", Integration: "GCP/Logging",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "2.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_log_sink", Title: "Log export sink configured", Severity: "medium", Integration: "GCP/Logging",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "2.2"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_log_metric_ownership", Title: "Log metric: project ownership changes", Severity: "medium", Integration: "GCP/Logging",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "2.4"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_log_metric_audit_config", Title: "Log metric: audit config changes", Severity: "medium", Integration: "GCP/Logging",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "2.5"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_log_metric_custom_role", Title: "Log metric: custom role changes", Severity: "medium", Integration: "GCP/Logging",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "2.6"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── GCP Networking ────────────────────────────────────────────────────────
	{ID: "gcp_firewall_ssh", Title: "No firewall rules allow SSH from 0.0.0.0/0", Severity: "critical", Integration: "GCP/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "3.1"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "gcp_firewall_rdp", Title: "No firewall rules allow RDP from 0.0.0.0/0", Severity: "critical", Integration: "GCP/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "3.2"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "gcp_vpc_flow_logs", Title: "VPC flow logs enabled on all subnets", Severity: "medium", Integration: "GCP/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "3.8"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_no_default_network", Title: "Default VPC network does not exist", Severity: "medium", Integration: "GCP/Network",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "3.1"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},
	{ID: "gcp_dns_logging", Title: "DNS logging enabled on private VPC zones", Severity: "medium", Integration: "GCP/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "3.7"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── GCP Storage ───────────────────────────────────────────────────────────
	{ID: "gcp_gcs_public_access", Title: "No GCS buckets publicly accessible", Severity: "critical", Integration: "GCP/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, {FrameworkCIS, "5.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_gcs_uniform_iam", Title: "GCS uniform bucket-level access enabled", Severity: "medium", Integration: "GCP/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_gcs_versioning", Title: "GCS bucket versioning enabled", Severity: "medium", Integration: "GCP/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "5.3"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "gcp_gcs_logging", Title: "GCS bucket access logging enabled", Severity: "medium", Integration: "GCP/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "5.4"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "gcp_gcs_cmek", Title: "GCS buckets encrypted with CMEK", Severity: "medium", Integration: "GCP/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "5.5"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},

	// ── GCP Compute & Cloud SQL ───────────────────────────────────────────────
	{ID: "gcp_cloudsql_ssl", Title: "Cloud SQL requires SSL connections", Severity: "high", Integration: "GCP/CloudSQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "6.3.7"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "gcp_cloudsql_public_ip", Title: "Cloud SQL has no public IP", Severity: "critical", Integration: "GCP/CloudSQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "6.4"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_cloudsql_backup", Title: "Cloud SQL automated backups enabled", Severity: "high", Integration: "GCP/CloudSQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.308(a)(7)"}, {FrameworkCIS, "6.7"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "gcp_vm_os_login", Title: "OS Login enabled at project level", Severity: "high", Integration: "GCP/Compute",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "4.4"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "gcp_vm_project_ssh_keys", Title: "No project-wide SSH keys configured", Severity: "medium", Integration: "GCP/Compute",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "4.3"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "gcp_vm_serial_port", Title: "VM serial port access disabled", Severity: "medium", Integration: "GCP/Compute",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "4.5"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "gcp_vm_shielded", Title: "Shielded VM (Secure Boot) enabled", Severity: "medium", Integration: "GCP/Compute",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "4.8"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},

	// ── GCP P2/P3 ─────────────────────────────────────────────────────────────
	{ID: "gcp_bigquery_public", Title: "BigQuery datasets not publicly accessible", Severity: "critical", Integration: "GCP/BigQuery",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_artifact_registry_scan", Title: "Artifact Registry container scanning enabled", Severity: "high", Integration: "GCP/ArtifactRegistry",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)(ii)(B)"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "gcp_cloudsql_cmek", Title: "Cloud SQL encrypted with CMEK", Severity: "high", Integration: "GCP/CloudSQL",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "gcp_gke_database_encryption", Title: "GKE application-layer secrets encryption enabled", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "gcp_kms_key_rotation", Title: "Cloud KMS key rotation enabled", Severity: "medium", Integration: "GCP/KMS",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.2"), PCIDSS("3.7.4")}},
	{ID: "gcp_vm_disk_cmek", Title: "VM persistent disks encrypted with CMEK", Severity: "medium", Integration: "GCP/Compute",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "gcp_scc_enabled", Title: "Security Command Center enabled", Severity: "high", Integration: "GCP/SCC",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},

	// ── GCP GKE (full set) ────────────────────────────────────────────────────
	{ID: "gcp_gke_private_cluster", Title: "GKE private nodes enabled", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.6.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_gke_workload_identity", Title: "GKE Workload Identity enabled", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkCIS, "6.2.1"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "gcp_gke_network_policy", Title: "GKE network policy enabled", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.6.7"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},
	{ID: "gcp_gke_master_auth_networks", Title: "GKE master authorized networks restricted", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.6.2"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_gke_shielded_nodes", Title: "GKE shielded nodes enabled", Severity: "medium", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.5.3"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "gcp_gke_legacy_metadata", Title: "GKE legacy metadata endpoints disabled", Severity: "medium", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.4.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "gcp_gke_auto_upgrade", Title: "GKE node auto-upgrade enabled", Severity: "medium", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "6.5.2"}, ISO27001("A.12.6.1"), PCIDSS("6.3.3")}},
	{ID: "gcp_gke_binary_auth", Title: "GKE Binary Authorization enabled", Severity: "high", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "6.10.1"}, ISO27001("A.12.5.1"), PCIDSS("6.3.2")}},
	{ID: "gcp_gke_intranode_visibility", Title: "GKE intranode visibility enabled", Severity: "low", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "6.6.5"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},
	{ID: "gcp_gke_release_channel", Title: "GKE release channel configured", Severity: "low", Integration: "GCP/GKE",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "6.5.1"}, ISO27001("A.12.6.1"), PCIDSS("6.3.3")}},

	// ── Azure Storage ─────────────────────────────────────────────────────────
	{ID: "az_storage_https", Title: "Azure Storage accounts enforce HTTPS-only", Severity: "high", Integration: "Azure/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(2)(ii)"}, {FrameworkCIS, "3.1"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "az_storage_public", Title: "No public blob access on Azure storage accounts", Severity: "critical", Integration: "Azure/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, {FrameworkCIS, "3.7"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "az_storage_tls", Title: "Azure Storage minimum TLS 1.2 enforced", Severity: "high", Integration: "Azure/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(e)(2)(ii)"}, {FrameworkCIS, "3.4"}, ISO27001("A.10.1.1"), PCIDSS("4.2.1")}},
	{ID: "az_storage_soft_delete", Title: "Azure blob soft delete enabled", Severity: "medium", Integration: "Azure/Storage",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.308(a)(7)"}, {FrameworkCIS, "3.8"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "az_storage_infra_encryption", Title: "Azure Storage infrastructure encryption enabled", Severity: "medium", Integration: "Azure/Storage",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},

	// ── Azure Networking ──────────────────────────────────────────────────────
	{ID: "az_nsg_rdp", Title: "No Azure NSG rules allow RDP from Internet", Severity: "critical", Integration: "Azure/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "6.1"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "az_nsg_ssh", Title: "No Azure NSG rules allow SSH from Internet", Severity: "critical", Integration: "Azure/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "6.2"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "az_nsg_flow_logs", Title: "Azure NSG flow logs configured", Severity: "medium", Integration: "Azure/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "6.4"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "az_network_watcher_all_regions", Title: "Azure Network Watcher enabled in all active regions", Severity: "medium", Integration: "Azure/Network",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "6.5"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},

	// ── Azure Compute & Encryption ────────────────────────────────────────────
	{ID: "az_disk_encryption", Title: "Azure VM managed disk encryption enabled", Severity: "high", Integration: "Azure/Compute",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "7.2"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "az_vm_backup", Title: "Azure VM backup configured", Severity: "high", Integration: "Azure/Compute",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.308(a)(7)"}, {FrameworkCIS, "7.4"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "az_vm_trusted_launch", Title: "Azure VM Trusted Launch / Secure Boot enabled", Severity: "medium", Integration: "Azure/Compute",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "7.5"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},

	// ── Azure Monitoring & Logging ────────────────────────────────────────────
	{ID: "az_defender", Title: "Microsoft Defender for Cloud enabled on key services", Severity: "high", Integration: "Azure/Defender",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, {FrameworkCIS, "2.1"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},
	{ID: "az_aks_defender_containers", Title: "Microsoft Defender for Containers on AKS enabled", Severity: "high", Integration: "Azure/Defender",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, {FrameworkCIS, "5.4.3"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},
	{ID: "az_activity_logs", Title: "Azure Activity Log diagnostic settings configured", Severity: "high", Integration: "Azure/Monitor",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "5.1.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "az_activity_log_retention", Title: "Azure Activity Log retention ≥ 365 days", Severity: "medium", Integration: "Azure/Monitor",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "5.1.2"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "az_log_alerts", Title: "Azure Activity Log alerts configured", Severity: "medium", Integration: "Azure/Monitor",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "5.2.1"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},

	// ── Azure SQL ─────────────────────────────────────────────────────────────
	{ID: "az_sql_auditing", Title: "Azure SQL Server auditing enabled", Severity: "high", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "4.1.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "az_sql_tde", Title: "Azure SQL Database Transparent Data Encryption enabled", Severity: "high", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "4.1.2"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "az_sql_threat", Title: "Azure SQL Advanced Threat Protection enabled", Severity: "high", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, {FrameworkCIS, "4.2.1"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},
	{ID: "az_sql_firewall", Title: "No Azure SQL Server firewall rule allows all IPs", Severity: "critical", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "4.3"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "az_sql_audit_retention", Title: "Azure SQL audit log retention ≥ 90 days", Severity: "medium", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkCIS, "4.1.3"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "az_sql_vuln_assessment", Title: "Azure SQL Vulnerability Assessment enabled", Severity: "high", Integration: "Azure/SQL",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)"}, {FrameworkCIS, "4.2.2"}, ISO27001("A.12.6.1"), PCIDSS("11.3.1")}},

	// ── Azure Key Vault ───────────────────────────────────────────────────────
	{ID: "az_keyvault_soft_delete", Title: "Azure Key Vault soft delete enabled", Severity: "high", Integration: "Azure/KeyVault",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "8.4"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "az_keyvault_purge_protection", Title: "Azure Key Vault purge protection enabled", Severity: "high", Integration: "Azure/KeyVault",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "az_keyvault_key_expiry", Title: "Azure Key Vault keys have expiration dates set", Severity: "medium", Integration: "Azure/KeyVault",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkCIS, "8.1"}, ISO27001("A.10.1.2"), PCIDSS("3.7.4")}},

	// ── Azure AKS ─────────────────────────────────────────────────────────────
	{ID: "az_aks_rbac", Title: "Azure AKS RBAC enabled", Severity: "high", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.308(a)(3)(i)"}, {FrameworkCIS, "5.1.1"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "az_aks_aad", Title: "Azure AKS Azure AD integration enabled", Severity: "high", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.308(a)(3)(i)"}, {FrameworkCIS, "5.2.1"}, ISO27001("A.9.2.3"), PCIDSS("8.2.1")}},
	{ID: "az_aks_network_policy", Title: "Azure AKS network policy configured", Severity: "high", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "5.3.2"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},
	{ID: "az_aks_private_cluster", Title: "Azure AKS private cluster or authorized IP ranges", Severity: "high", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "5.4.1"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "az_aks_node_auto_upgrade", Title: "AKS node OS auto-upgrade enabled", Severity: "medium", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)"}, {FrameworkCIS, "5.4.2"}, ISO27001("A.12.6.1"), PCIDSS("6.3.3")}},
	{ID: "az_aks_csi_secrets", Title: "AKS uses Secrets Store CSI Driver for Key Vault", Severity: "medium", Integration: "Azure/AKS",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "5.1.2"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},

	// ── Azure IAM / Identity ──────────────────────────────────────────────────
	{ID: "az_mfa_conditional_access", Title: "Azure AD Conditional Access requires MFA", Severity: "critical", Integration: "Azure/AAD",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(d)"}, {FrameworkCIS, "1.2.1"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "az_no_guest_admin", Title: "No Azure guest users with administrative roles", Severity: "high", Integration: "Azure/AAD",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.308(a)(3)"}, {FrameworkCIS, "1.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "az_pim_enabled", Title: "Azure Privileged Identity Management (PIM) in use", Severity: "high", Integration: "Azure/AAD",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.308(a)(3)"}, {FrameworkCIS, "1.14"}, ISO27001("A.9.2.5"), PCIDSS("7.2.1")}},

	// ── Kubernetes Pod & Container Security ───────────────────────────────────
	{ID: "k8s_privileged", Title: "No privileged containers running", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(a)(1)"}, {FrameworkCIS, "5.2.1"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_root_user", Title: "No containers running as root (UID 0)", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.6"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_host_network", Title: "No hostNetwork sharing in pods", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.4"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "k8s_host_pid", Title: "No hostPID sharing in pods", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.2"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_host_ipc", Title: "No hostIPC sharing in pods", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.3"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_host_namespace", Title: "No pods sharing host namespaces", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_resource_limits", Title: "All containers have resource limits set", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.12"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_readonly_rootfs", Title: "Containers use read-only root filesystem", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.8"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_privilege_escalation", Title: "No privilege escalation allowed in containers", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.5"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_capability_drop", Title: "Containers drop all Linux capabilities", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.7"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_hostpath_mounts", Title: "No writable hostPath volume mounts", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.9"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_seccomp", Title: "Seccomp profile set on pods", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.7.2"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_psa", Title: "Pod Security Admission labels on all workload namespaces", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.1"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_secrets_env_vars", Title: "No plaintext secrets in pod environment variables", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "5.4.1"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},

	// ── Kubernetes RBAC ───────────────────────────────────────────────────────
	{ID: "k8s_cluster_admin", Title: "No unexpected cluster-admin ClusterRoleBindings", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.308(a)(3)(i)"}, {FrameworkCIS, "5.1.1"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_wildcard_roles", Title: "No wildcard verbs or resources in RBAC roles", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "5.1.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_sa_token_automount", Title: "Service accounts disable token auto-mounting", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "5.1.6"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_bind_escalate", Title: "No bind/escalate/impersonate verbs in RBAC roles", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkCIS, "5.1.5"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},

	// ── Kubernetes Networking & Admission ─────────────────────────────────────
	{ID: "k8s_default_deny", Title: "Namespaces have default-deny network policies", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, {FrameworkCIS, "5.3.1"}, ISO27001("A.13.1.1"), PCIDSS("1.2.7")}},

	// ── Kubernetes P1 ─────────────────────────────────────────────────────────
	{ID: "k8s_image_pull_always", Title: "Containers use specific image tags (not :latest)", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkCIS, "5.5.1"}, ISO27001("A.12.5.1"), PCIDSS("6.3.2")}},
	{ID: "k8s_non_root_uid", Title: "Containers run as UID > 0 (non-root numeric user)", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.2.6"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "k8s_resource_requests", Title: "All containers have resource requests set", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_image_registry", Title: "Container images pulled from approved registries only", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, ISO27001("A.12.5.1"), PCIDSS("6.3.2")}},

	// ── Kubernetes P2 ─────────────────────────────────────────────────────────
	{ID: "k8s_etcd_encryption", Title: "etcd secrets encrypted at rest", Severity: "critical", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, {FrameworkCIS, "5.4.2"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "k8s_opa_gatekeeper", Title: "OPA Gatekeeper or Kyverno admission controller active", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_apparmor", Title: "AppArmor profiles applied to containers", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkCIS, "5.7.3"}, ISO27001("A.13.1.3"), PCIDSS("6.3.1")}},
	{ID: "k8s_external_secrets", Title: "External Secrets Operator or CSI driver in use", Severity: "medium", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},
	{ID: "k8s_audit_logging", Title: "Kubernetes audit logging enabled and retained", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, {FrameworkHIPAA, "164.312(b)"}, {FrameworkCIS, "3.2.1"}, ISO27001("A.12.4.1"), PCIDSS("10.2.1")}},
	{ID: "k8s_falco", Title: "Falco runtime threat detection running", Severity: "high", Integration: "Kubernetes",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, {FrameworkHIPAA, "164.308(a)(1)(ii)(D)"}, ISO27001("A.16.1.2"), PCIDSS("10.7.1")}},

	// ── GitHub Repository Security ────────────────────────────────────────────
	{ID: "github_public_repos", Title: "No unexpected public GitHub repositories", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.308(a)(4)(i)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "github_dependabot", Title: "Dependabot security updates configured", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "github_required_status_checks", Title: "Required status checks before merge", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.1.4"), PCIDSS("6.2.4")}},
	{ID: "github_push_protection", Title: "Secret scanning push protection enabled", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.8"}, ISO27001("A.9.4.1"), PCIDSS("6.3.2")}},
	{ID: "github_token_permissions", Title: "GITHUB_TOKEN permissions scoped to read-only", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, ISO27001("A.9.2.3"), PCIDSS("7.2.1")}},
	{ID: "github_no_self_hosted_public", Title: "No self-hosted runners on public repositories", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},

	// ── GitHub CI/CD ──────────────────────────────────────────────────────────
	{ID: "github_actions_pinned", Title: "GitHub Actions pinned to full commit SHA", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.5.1"), PCIDSS("6.3.2")}},
	{ID: "github_actions_prt", Title: "No unsafe pull_request_target + head checkout", Severity: "critical", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.1.4"), PCIDSS("6.2.4")}},
	{ID: "github_env_protection", Title: "Production environments require reviewer approval", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.1.4"), PCIDSS("6.2.4")}},

	// ── GitHub Organization ───────────────────────────────────────────────────
	{ID: "github_org_2fa", Title: "GitHub organization requires 2FA for all members", Severity: "critical", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.312(d)"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "github_org_sso", Title: "SAML SSO enforced for GitHub organization", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.308(a)(5)"}, ISO27001("A.9.4.2"), PCIDSS("8.4.2")}},
	{ID: "github_org_outside_collab", Title: "Outside collaborators reviewed", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.3"}, {FrameworkHIPAA, "164.308(a)(3)"}, ISO27001("A.9.2.2"), PCIDSS("7.2.1")}},
	{ID: "github_code_scanning", Title: "Code scanning (SAST / CodeQL) enabled", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},

	// ── GitHub P1/P2 ──────────────────────────────────────────────────────────
	{ID: "github_codeowners", Title: "CODEOWNERS file exists in all repositories", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.9.2.2"), PCIDSS("6.2.4")}},
	{ID: "github_dependabot_alerts", Title: "Dependabot security alerts enabled on all repos", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.1"}, {FrameworkHIPAA, "164.308(a)(5)"}, ISO27001("A.12.6.1"), PCIDSS("6.3.2")}},
	{ID: "github_branch_dismiss_stale", Title: "Branch protection dismisses stale reviews on new commits", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC8.1"}, ISO27001("A.12.1.4"), PCIDSS("6.2.4")}},
	{ID: "github_oidc_cloud_auth", Title: "OIDC used for cloud auth — no long-lived secrets in workflows", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, {FrameworkHIPAA, "164.308(a)(3)"}, ISO27001("A.9.4.3"), PCIDSS("8.3.1")}},
	{ID: "github_verified_domains", Title: "GitHub organization has verified domains", Severity: "low", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.1.2"), PCIDSS("7.2.3")}},
	{ID: "github_org_ip_allowlist", Title: "GitHub organization IP allowlist enabled", Severity: "high", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.9.1.2"), PCIDSS("1.3.2")}},
	{ID: "github_secret_rotation", Title: "Repository secrets have expiry / rotation policy", Severity: "medium", Integration: "GitHub",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.1"}, ISO27001("A.9.4.3"), PCIDSS("8.3.9")}},

	// ── Terraform (additional) ────────────────────────────────────────────────
	{ID: "tf_s3_no_public_acl", Title: "S3 buckets have no public ACL in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(1)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "tf_s3_public_access_block", Title: "S3 public access block enabled in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "tf_s3_encryption", Title: "S3 server-side encryption enabled in Terraform", Severity: "high", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.10.1.1"), PCIDSS("3.5.1")}},
	{ID: "tf_s3_versioning", Title: "S3 versioning enabled in Terraform", Severity: "medium", Integration: "Terraform",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.2"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "tf_sg_rdp_restricted", Title: "RDP not open to 0.0.0.0/0 in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.1"), PCIDSS("1.2.1")}},
	{ID: "tf_sg_no_open_all", Title: "No 0.0.0.0/0 ingress on all ports in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.1"), PCIDSS("1.2.2")}},
	{ID: "tf_rds_not_public", Title: "RDS publicly_accessible = false in Terraform", Severity: "critical", Integration: "Terraform",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, {FrameworkHIPAA, "164.312(e)(2)(i)"}, ISO27001("A.13.1.3"), PCIDSS("1.3.2")}},
	{ID: "tf_rds_deletion_protection", Title: "RDS deletion protection enabled in Terraform", Severity: "medium", Integration: "Terraform",
		Frameworks: []string{"soc2", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "tf_ec2_imdsv2", Title: "EC2 IMDSv2 enforced in Terraform", Severity: "high", Integration: "Terraform",
		Frameworks: []string{"soc2", "cis", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.6"}, ISO27001("A.13.1.3"), PCIDSS("6.3.3")}},

	// ── Policy / Cross-cutting ────────────────────────────────────────────────
	{ID: "cross_backup_restore_test", Title: "Backup restore testing evidence documented", Severity: "high", Integration: "Policy",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.1"}, {FrameworkHIPAA, "164.308(a)(7)(ii)(D)"}, ISO27001("A.12.3.1"), PCIDSS("12.3.4")}},
	{ID: "cross_incident_response", Title: "Incident response runbook documented", Severity: "high", Integration: "Policy",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC7.3"}, {FrameworkHIPAA, "164.308(a)(6)"}, ISO27001("A.16.1.5"), PCIDSS("12.10.1")}},
	{ID: "cross_pen_test", Title: "Annual penetration test evidence on file", Severity: "high", Integration: "Policy",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC4.1"}, {FrameworkHIPAA, "164.308(a)(8)"}, ISO27001("A.18.2.3"), PCIDSS("11.4.1")}},
	{ID: "cross_data_classification", Title: "PII/PHI data stores tagged with DataClassification", Severity: "medium", Integration: "Policy",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC6.7"}, {FrameworkHIPAA, "164.312(a)(2)(iv)"}, ISO27001("A.8.2.1"), PCIDSS("3.3.1")}},
	{ID: "cross_vendor_risk", Title: "Vendor risk register documented", Severity: "medium", Integration: "Policy",
		Frameworks: []string{"soc2", "hipaa", "iso27001", "pcidss"},
		Controls:   []ControlRef{{FrameworkSOC2, "CC9.2"}, {FrameworkHIPAA, "164.308(b)"}, ISO27001("A.15.1.1"), PCIDSS("12.8.1")}}}
