package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const ConfigFile = ".complykit.yml"

type Config struct {
	Framework  string     `yaml:"framework"`
	AWS        AWSConfig  `yaml:"aws,omitempty"`
	GCP        GCPConfig  `yaml:"gcp,omitempty"`
	GitHub     GHConfig   `yaml:"github,omitempty"`
	Alerts     AlertsConf `yaml:"alerts,omitempty"`
	OutputDir  string     `yaml:"output_dir,omitempty"`
}

type AWSConfig struct {
	Profile string `yaml:"profile,omitempty"`
	Region  string `yaml:"region,omitempty"`
	Enabled bool   `yaml:"enabled"`
}

type GCPConfig struct {
	ProjectID string `yaml:"project_id,omitempty"`
	Enabled   bool   `yaml:"enabled"`
}

type GHConfig struct {
	Owner   string `yaml:"owner,omitempty"`
	Enabled bool   `yaml:"enabled"`
}

type AlertsConf struct {
	SlackWebhook string `yaml:"slack_webhook,omitempty"`
	EmailTo      string `yaml:"email_to,omitempty"`
	EmailFrom    string `yaml:"email_from,omitempty"`
	SMTPHost     string `yaml:"smtp_host,omitempty"`
	SMTPPort     int    `yaml:"smtp_port,omitempty"`
	SMTPUser     string `yaml:"smtp_user,omitempty"`
	SMTPPass     string `yaml:"smtp_pass,omitempty"`
}

func Load() (*Config, error) {
	data, err := os.ReadFile(ConfigFile)
	if err != nil {
		return nil, fmt.Errorf("no config found — run `comply init` first")
	}
	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("invalid config file: %w", err)
	}
	return &cfg, nil
}

func Save(cfg *Config) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}
	header := "# ComplyKit configuration — generated by `comply init`\n# Edit manually or re-run `comply init` to reconfigure\n\n"
	return os.WriteFile(ConfigFile, append([]byte(header), data...), 0600)
}

func Exists() bool {
	_, err := os.Stat(ConfigFile)
	return err == nil
}

func DefaultOutputDir() string {
	return filepath.Join(".", "comply-reports")
}
